version: "3.9"
services:
  client:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ../inventarium/dist/inventarium:/usr/share/nginx/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
  db:
    container_name: inventarium_sql
    image: mariadb:10.7.1-focal
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
      - ./config-database/my.cnf:/etc/mysql/my.cnf
    networks:
      - default
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ualinventarium
      MYSQL_USER: ualinventarium
      MYSQL_PASSWORD: uS3rP4ssM0Ord20D1f1CIL3
      MYSQL_ROOT_PASSWORD: rO0trP4ssM0Ord20D1f1CIL3
    depends_on:
      - "client"
  phpmyadmin:
    container_name: inventarium_php_adm
    image: phpmyadmin:5.1
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: ualinventarium
      MYSQL_PASSWORD: uS3rP4ssM0Ord20D1f1CIL3
      MYSQL_ROOT_PASSWORD: rO0trP4ssM0Ord20D1f1CIL3
    networks:
      - default
    depends_on:
      - "db"
  backup:
    image: databack/mysql-backup
    restart: always
    volumes:
      - ./backup:/db
    environment:
      DB_DUMP_TARGET: /db
      DB_USER: root
      DB_PASS: rO0trP4ssM0Ord20D1f1CIL3
      DB_DUMP_FREQ: 720
      DB_DUMP_BEGIN: 2330
      DB_SERVER: db
      DB_NAMES: ualinventarium
      DB_PORT: 3306
    depends_on:
      - "db"
  api:
    build:
      context: ../API
      dockerfile: ../API/Dockerfile
    image: node:16.4
    restart: always
    container_name: api
    volumes:
      - ../API:/app
    networks:
      - default
volumes:
  persistent: {}
