version: "3.9"
services:
  db:
    container_name: inventarium_sql
    image: mariadb:10.7.1-focal
    ports:
      - "3306:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
    environment:
      MYSQL_DATABASE: ualinventarium
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
  phpmyadmin:
    container_name: inventarium_php_adm
    image: phpmyadmin:5.1
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    networks:
      - default
volumes:
  persistent: {}
